export interface Country {
  name: string;
  iso2: string;
  iso3: string;
}

export const PRIORITY_COUNTRIES: Country[] = [
  { name: "Slovensko", iso2: "SK", iso3: "SVK" },
  { name: "Česko", iso2: "CZ", iso3: "CZE" },
  { name: "Rakúsko", iso2: "AT", iso3: "AUT" },
  { name: "Maďarsko", iso2: "HU", iso3: "HUN" },
  { name: "Poľsko", iso2: "PL", iso3: "POL" },
  { name: "Ukrajina", iso2: "UA", iso3: "UKR" },
  { name: "Nemecko", iso2: "DE", iso3: "DEU" },
];

export const ALL_COUNTRIES: Country[] = [
  { name: "Afganistan", iso2: "AF", iso3: "AFG" },
  { name: "Albánsko", iso2: "AL", iso3: "ALB" },
  { name: "Alžírsko", iso2: "DZ", iso3: "DZA" },
  { name: "Andorra", iso2: "AD", iso3: "AND" },
  { name: "Angola", iso2: "AO", iso3: "AGO" },
  { name: "Antigua a Barbuda", iso2: "AG", iso3: "ATG" },
  { name: "Argentína", iso2: "AR", iso3: "ARG" },
  { name: "Arménsko", iso2: "AM", iso3: "ARM" },
  { name: "Austrália", iso2: "AU", iso3: "AUS" },
  { name: "Azerbajdžan", iso2: "AZ", iso3: "AZE" },
  { name: "Bahamy", iso2: "BS", iso3: "BHS" },
  { name: "Bahrajn", iso2: "BH", iso3: "BHR" },
  { name: "Bangladéš", iso2: "BD", iso3: "BGD" },
  { name: "Barbados", iso2: "BB", iso3: "BRB" },
  { name: "Belgicko", iso2: "BE", iso3: "BEL" },
  { name: "Belize", iso2: "BZ", iso3: "BLZ" },
  { name: "Benin", iso2: "BJ", iso3: "BEN" },
  { name: "Bielorusko", iso2: "BY", iso3: "BLR" },
  { name: "Bhután", iso2: "BT", iso3: "BTN" },
  { name: "Bolívia", iso2: "BO", iso3: "BOL" },
  { name: "Bosna a Hercegovina", iso2: "BA", iso3: "BIH" },
  { name: "Botswana", iso2: "BW", iso3: "BWA" },
  { name: "Brazília", iso2: "BR", iso3: "BRA" },
  { name: "Brunej", iso2: "BN", iso3: "BRN" },
  { name: "Bulharsko", iso2: "BG", iso3: "BGR" },
  { name: "Burkina Faso", iso2: "BF", iso3: "BFA" },
  { name: "Burundi", iso2: "BI", iso3: "BDI" },
  { name: "Cyprus", iso2: "CY", iso3: "CYP" },
  { name: "Čad", iso2: "TD", iso3: "TCD" },
  { name: "Čierna Hora", iso2: "ME", iso3: "MNE" },
  { name: "Česko", iso2: "CZ", iso3: "CZE" },
  { name: "Čile", iso2: "CL", iso3: "CHL" },
  { name: "Čína", iso2: "CN", iso3: "CHN" },
  { name: "Dánsko", iso2: "DK", iso3: "DNK" },
  { name: "Dominika", iso2: "DM", iso3: "DMA" },
  { name: "Dominikánska republika", iso2: "DO", iso3: "DOM" },
  { name: "Džibutsko", iso2: "DJ", iso3: "DJI" },
  { name: "Egypt", iso2: "EG", iso3: "EGY" },
  { name: "Ekvádor", iso2: "EC", iso3: "ECU" },
  { name: "Eritrea", iso2: "ER", iso3: "ERI" },
  { name: "Estónsko", iso2: "EE", iso3: "EST" },
  { name: "Eswatini", iso2: "SZ", iso3: "SWZ" },
  { name: "Etiópia", iso2: "ET", iso3: "ETH" },
  { name: "Fidži", iso2: "FJ", iso3: "FJI" },
  { name: "Filipíny", iso2: "PH", iso3: "PHL" },
  { name: "Fínsko", iso2: "FI", iso3: "FIN" },
  { name: "Francúzsko", iso2: "FR", iso3: "FRA" },
  { name: "Gabon", iso2: "GA", iso3: "GAB" },
  { name: "Gambia", iso2: "GM", iso3: "GMB" },
  { name: "Ghana", iso2: "GH", iso3: "GHA" },
  { name: "Grenada", iso2: "GD", iso3: "GRD" },
  { name: "Grécko", iso2: "GR", iso3: "GRC" },
  { name: "Gruzínsko", iso2: "GE", iso3: "GEO" },
  { name: "Guatemala", iso2: "GT", iso3: "GTM" },
  { name: "Guinea", iso2: "GN", iso3: "GIN" },
  { name: "Guinea-Bissau", iso2: "GW", iso3: "GNB" },
  { name: "Guyana", iso2: "GY", iso3: "GUY" },
  { name: "Haiti", iso2: "HT", iso3: "HTI" },
  { name: "Holandsko", iso2: "NL", iso3: "NLD" },
  { name: "Honduras", iso2: "HN", iso3: "HND" },
  { name: "Chorvátsko", iso2: "HR", iso3: "HRV" },
  { name: "India", iso2: "IN", iso3: "IND" },
  { name: "Indonézia", iso2: "ID", iso3: "IDN" },
  { name: "Irak", iso2: "IQ", iso3: "IRQ" },
  { name: "Irán", iso2: "IR", iso3: "IRN" },
  { name: "Írsko", iso2: "IE", iso3: "IRL" },
  { name: "Island", iso2: "IS", iso3: "ISL" },
  { name: "Izrael", iso2: "IL", iso3: "ISR" },
  { name: "Jamajka", iso2: "JM", iso3: "JAM" },
  { name: "Japonsko", iso2: "JP", iso3: "JPN" },
  { name: "Jemen", iso2: "YE", iso3: "YEM" },
  { name: "Jordánsko", iso2: "JO", iso3: "JOR" },
  { name: "Južná Afrika", iso2: "ZA", iso3: "ZAF" },
  { name: "Južný Sudán", iso2: "SS", iso3: "SSD" },
  { name: "Kambodža", iso2: "KH", iso3: "KHM" },
  { name: "Kamerun", iso2: "CM", iso3: "CMR" },
  { name: "Kanada", iso2: "CA", iso3: "CAN" },
  { name: "Kapverdy", iso2: "CV", iso3: "CPV" },
  { name: "Katar", iso2: "QA", iso3: "QAT" },
  { name: "Kazachstan", iso2: "KZ", iso3: "KAZ" },
  { name: "Keňa", iso2: "KE", iso3: "KEN" },
  { name: "Kirgizsko", iso2: "KG", iso3: "KGZ" },
  { name: "Kiribati", iso2: "KI", iso3: "KIR" },
  { name: "Kolumbia", iso2: "CO", iso3: "COL" },
  { name: "Komory", iso2: "KM", iso3: "COM" },
  { name: "Kongo (Dem. rep.)", iso2: "CD", iso3: "COD" },
  { name: "Kongo (Rep.)", iso2: "CG", iso3: "COG" },
  { name: "Kórejská ľudovodem. rep. (Severná)", iso2: "KP", iso3: "PRK" },
  { name: "Kórejská republika (Južná)", iso2: "KR", iso3: "KOR" },
  { name: "Kostarika", iso2: "CR", iso3: "CRI" },
  { name: "Kuba", iso2: "CU", iso3: "CUB" },
  { name: "Kuvajt", iso2: "KW", iso3: "KWT" },
  { name: "Laos", iso2: "LA", iso3: "LAO" },
  { name: "Lesotho", iso2: "LS", iso3: "LSO" },
  { name: "Lotyšsko", iso2: "LV", iso3: "LVA" },
  { name: "Libanon", iso2: "LB", iso3: "LBN" },
  { name: "Libéria", iso2: "LR", iso3: "LBR" },
  { name: "Líbya", iso2: "LY", iso3: "LBY" },
  { name: "Lichtenštajnsko", iso2: "LI", iso3: "LIE" },
  { name: "Litva", iso2: "LT", iso3: "LTU" },
  { name: "Luxembursko", iso2: "LU", iso3: "LUX" },
  { name: "Madagaskar", iso2: "MG", iso3: "MDG" },
  { name: "Maďarsko", iso2: "HU", iso3: "HUN" },
  { name: "Malajzia", iso2: "MY", iso3: "MYS" },
  { name: "Malawi", iso2: "MW", iso3: "MWI" },
  { name: "Maldivy", iso2: "MV", iso3: "MDV" },
  { name: "Mali", iso2: "ML", iso3: "MLI" },
  { name: "Malta", iso2: "MT", iso3: "MLT" },
  { name: "Maroko", iso2: "MA", iso3: "MAR" },
  { name: "Marshallove ostrovy", iso2: "MH", iso3: "MHL" },
  { name: "Maurícius", iso2: "MU", iso3: "MUS" },
  { name: "Mauritánia", iso2: "MR", iso3: "MRT" },
  { name: "Mexiko", iso2: "MX", iso3: "MEX" },
  { name: "Mikronézia", iso2: "FM", iso3: "FSM" },
  { name: "Mjanmarsko", iso2: "MM", iso3: "MMR" },
  { name: "Moldavsko", iso2: "MD", iso3: "MDA" },
  { name: "Monako", iso2: "MC", iso3: "MCO" },
  { name: "Mongolsko", iso2: "MN", iso3: "MNG" },
  { name: "Mozambik", iso2: "MZ", iso3: "MOZ" },
  { name: "Namíbia", iso2: "NA", iso3: "NAM" },
  { name: "Nauru", iso2: "NR", iso3: "NRU" },
  { name: "Nemecko", iso2: "DE", iso3: "DEU" },
  { name: "Nepál", iso2: "NP", iso3: "NPL" },
  { name: "Niger", iso2: "NE", iso3: "NER" },
  { name: "Nigéria", iso2: "NG", iso3: "NGA" },
  { name: "Nikaragua", iso2: "NI", iso3: "NIC" },
  { name: "Niue", iso2: "NU", iso3: "NIU" },
  { name: "Nórsko", iso2: "NO", iso3: "NOR" },
  { name: "Nový Zéland", iso2: "NZ", iso3: "NZL" },
  { name: "Omán", iso2: "OM", iso3: "OMN" },
  { name: "Pakistan", iso2: "PK", iso3: "PAK" },
  { name: "Palau", iso2: "PW", iso3: "PLW" },
  { name: "Palestína", iso2: "PS", iso3: "PSE" },
  { name: "Panama", iso2: "PA", iso3: "PAN" },
  { name: "Papua-Nová Guinea", iso2: "PG", iso3: "PNG" },
  { name: "Paraguaj", iso2: "PY", iso3: "PRY" },
  { name: "Peru", iso2: "PE", iso3: "PER" },
  { name: "Pobrežie Slonoviny", iso2: "CI", iso3: "CIV" },
  { name: "Poľsko", iso2: "PL", iso3: "POL" },
  { name: "Portugalsko", iso2: "PT", iso3: "PRT" },
  { name: "Rakúsko", iso2: "AT", iso3: "AUT" },
  { name: "Rovníková Guinea", iso2: "GQ", iso3: "GNQ" },
  { name: "Rumunsko", iso2: "RO", iso3: "ROU" },
  { name: "Rusko", iso2: "RU", iso3: "RUS" },
  { name: "Rwanda", iso2: "RW", iso3: "RWA" },
  { name: "Salvador", iso2: "SV", iso3: "SLV" },
  { name: "Samoa", iso2: "WS", iso3: "WSM" },
  { name: "San Maríno", iso2: "SM", iso3: "SMR" },
  { name: "Saudská Arábia", iso2: "SA", iso3: "SAU" },
  { name: "Senegal", iso2: "SN", iso3: "SEN" },
  { name: "Severné Macedónsko", iso2: "MK", iso3: "MKD" },
  { name: "Seychely", iso2: "SC", iso3: "SYC" },
  { name: "Sierra Leone", iso2: "SL", iso3: "SLE" },
  { name: "Singapur", iso2: "SG", iso3: "SGP" },
  { name: "Slovensko", iso2: "SK", iso3: "SVK" },
  { name: "Slovinsko", iso2: "SI", iso3: "SVN" },
  { name: "Šalamúnove ostrovy", iso2: "SB", iso3: "SLB" },
  { name: "Somálsko", iso2: "SO", iso3: "SOM" },
  { name: "Spojené arabské emiráty", iso2: "AE", iso3: "ARE" },
  { name: "Spojené kráľovstvo", iso2: "GB", iso3: "GBR" },
  { name: "Spojené štáty americké", iso2: "US", iso3: "USA" },
  { name: "Srbsko", iso2: "RS", iso3: "SRB" },
  { name: "Srí Lanka", iso2: "LK", iso3: "LKA" },
  { name: "Stredoafrická republika", iso2: "CF", iso3: "CAF" },
  { name: "Sudán", iso2: "SD", iso3: "SDN" },
  { name: "Surinam", iso2: "SR", iso3: "SUR" },
  { name: "Svätá Lucia", iso2: "LC", iso3: "LCA" },
  { name: "Svätý Krištof a Nevis", iso2: "KN", iso3: "KNA" },
  { name: "Svätý Tomáš a Princov ostrov", iso2: "ST", iso3: "STP" },
  { name: "Svätý Vincent a Grenadíny", iso2: "VC", iso3: "VCT" },
  { name: "Sýria", iso2: "SY", iso3: "SYR" },
  { name: "Španielsko", iso2: "ES", iso3: "ESP" },
  { name: "Švajčiarsko", iso2: "CH", iso3: "CHE" },
  { name: "Švédsko", iso2: "SE", iso3: "SWE" },
  { name: "Tadžikistan", iso2: "TJ", iso3: "TJK" },
  { name: "Taiwan", iso2: "TW", iso3: "TWN" },
  { name: "Taliansko", iso2: "IT", iso3: "ITA" },
  { name: "Tanzánia", iso2: "TZ", iso3: "TZA" },
  { name: "Thajsko", iso2: "TH", iso3: "THA" },
  { name: "Togo", iso2: "TG", iso3: "TGO" },
  { name: "Tonga", iso2: "TO", iso3: "TON" },
  { name: "Trinidad a Tobago", iso2: "TT", iso3: "TTO" },
  { name: "Tunisko", iso2: "TN", iso3: "TUN" },
  { name: "Turecko", iso2: "TR", iso3: "TUR" },
  { name: "Turkménsko", iso2: "TM", iso3: "TKM" },
  { name: "Tuvalu", iso2: "TV", iso3: "TUV" },
  { name: "Uganda", iso2: "UG", iso3: "UGA" },
  { name: "Ukrajina", iso2: "UA", iso3: "UKR" },
  { name: "Uruguaj", iso2: "UY", iso3: "URY" },
  { name: "Uzbekistan", iso2: "UZ", iso3: "UZB" },
  { name: "Vanuatu", iso2: "VU", iso3: "VUT" },
  { name: "Vatikán", iso2: "VA", iso3: "VAT" },
  { name: "Venezuela", iso2: "VE", iso3: "VEN" },
  { name: "Vietnam", iso2: "VN", iso3: "VNM" },
  { name: "Východný Timor", iso2: "TL", iso3: "TLS" },
  { name: "Zambia", iso2: "ZM", iso3: "ZMB" },
  { name: "Zimbabwe", iso2: "ZW", iso3: "ZWE" },
];

export const PRIORITY_COUNTRY_NAMES = PRIORITY_COUNTRIES.map(c => c.name);
export const ALL_COUNTRY_NAMES = ALL_COUNTRIES.map(c => c.name);

export const DEFAULT_COUNTRY = "Slovensko";

export function getCountryIso(countryName: string): { iso2: string; iso3: string } | undefined {
  const all = [...PRIORITY_COUNTRIES, ...ALL_COUNTRIES];
  return all.find(c => c.name === countryName);
}

export function getCountryOptions() {
  const prioritySet = new Set(PRIORITY_COUNTRY_NAMES);
  const rest = ALL_COUNTRY_NAMES.filter(c => !prioritySet.has(c));
  return { priority: PRIORITY_COUNTRY_NAMES, rest };
}

export function getDefaultCountryForState(stateName?: string | null): string {
  return DEFAULT_COUNTRY;
}
