export interface StaticField {
  id: number;
  clientTypeId: number;
  sectionId: number | null;
  panelId: number | null;
  fieldKey: string;
  label: string;
  shortLabel?: string;
  fieldType: string;
  isRequired: boolean;
  isHidden: boolean;
  options: string[];
  defaultValue: string | null;
  visibilityRule: { dependsOn: string; value: string } | null;
  unit: string | null;
  decimalPlaces: number;
  fieldCategory: string;
  categoryCode?: string;
  sortOrder: number;
  rowNumber: number;
  widthPercent: number;
}

export interface StaticSection {
  id: number;
  clientTypeId: number;
  name: string;
  folderCategory: string;
  sortOrder: number;
}

export interface StaticPanel {
  id: number;
  clientTypeId: number;
  sectionId: number | null;
  name: string;
  gridColumns: number;
  sortOrder: number;
}

const FO_SECTION_POVINNE = 9;
const FO_SECTION_DOPLNKOVE = 17;
const FO_SECTION_VOLITELNE = 10;
const FO_PANEL_OSOBNE = 4;
const FO_PANEL_ADRESA = 5;
const FO_PANEL_CUDZINEC = 3;
const FO_PANEL_KONTAKT = 6;
const FO_PANEL_DOKLADY = 20;

const FO_PANEL_RODINA = 22;
const FO_PANEL_DORUCOVACIA = 23;
const FO_PANEL_AML = 24;
const FO_PANEL_ZAKONNE = 25;
const FO_PANEL_ZMLUVNE = 26;
const FO_PANEL_MAJETKOVE = 27;

const SZCO_SECTION_POVINNE = 11;
const SZCO_SECTION_DOPLNKOVE = 18;
const SZCO_SECTION_VOLITELNE = 12;
const SZCO_PANEL_SUBJEKT = 7;
const SZCO_PANEL_SIDLO = 8;
const SZCO_PANEL_OSOBNE = 9;
const SZCO_PANEL_ADRESA = 10;
const SZCO_PANEL_KONTAKT = 11;
const SZCO_PANEL_DOKLADY = 21;

const SZCO_PANEL_AML = 30;
const SZCO_PANEL_FIREMNY = 31;
const SZCO_PANEL_ZAKONNE = 34;
const SZCO_PANEL_ZMLUVNE = 35;

const PO_SECTION_POVINNE = 15;
const PO_SECTION_DOPLNKOVE = 19;
const PO_SECTION_VOLITELNE = 16;
const PO_PANEL_SUBJEKT = 13;
const PO_PANEL_SIDLO = 14;
const PO_PANEL_KONTAKT = 15;
const PO_PANEL_AML = 32;
const PO_PANEL_FIREMNY = 33;
const PO_PANEL_ZAKONNE = 36;
const PO_PANEL_ZMLUVNE = 37;
const PO_PANEL_STATUTARI = 38;

export const FO_SECTIONS: StaticSection[] = [
  { id: FO_SECTION_POVINNE, clientTypeId: 1, name: "POVINNÉ ÚDAJE", folderCategory: "povinne", sortOrder: 0 },
  { id: FO_SECTION_DOPLNKOVE, clientTypeId: 1, name: "DOPLNKOVÉ ÚDAJE", folderCategory: "doplnkove", sortOrder: 1 },
  { id: FO_SECTION_VOLITELNE, clientTypeId: 1, name: "VOLITEĽNÉ ÚDAJE", folderCategory: "volitelne", sortOrder: 2 },
];

export const FO_PANELS: StaticPanel[] = [
  { id: FO_PANEL_OSOBNE, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, name: "Osobné údaje", gridColumns: 5, sortOrder: 0 },
  { id: FO_PANEL_ADRESA, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, name: "Adresa", gridColumns: 4, sortOrder: 1 },
  { id: FO_PANEL_CUDZINEC, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, name: "Cudzinec bez rodného čísla", gridColumns: 1, sortOrder: 2 },
  { id: FO_PANEL_DOKLADY, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, name: "Doklady", gridColumns: 4, sortOrder: 3 },
  { id: FO_PANEL_KONTAKT, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, name: "Kontaktné údaje", gridColumns: 2, sortOrder: 4 },
  { id: FO_PANEL_RODINA, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, name: "Rodinný kontakt a zastihnutie", gridColumns: 2, sortOrder: 0 },
  { id: FO_PANEL_DORUCOVACIA, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, name: "Doručovacia adresa", gridColumns: 4, sortOrder: 1 },
  { id: FO_PANEL_AML, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, name: "AML – PEP a KUV", gridColumns: 3, sortOrder: 2 },
  { id: FO_PANEL_ZAKONNE, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, name: "Zákonné údaje", gridColumns: 2, sortOrder: 3 },
  { id: FO_PANEL_ZMLUVNE, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, name: "Bankové údaje", gridColumns: 3, sortOrder: 4 },
  { id: FO_PANEL_MAJETKOVE, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, name: "Majetkové údaje", gridColumns: 2, sortOrder: 5 },
];

export const FO_FIELDS: StaticField[] = [
  { id: 9, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "titul_pred", label: "Titul pred menom", shortLabel: "Titul pred", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 1, widthPercent: 12 },
  { id: 109, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "meno", label: "Meno", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 1, widthPercent: 33 },
  { id: 11, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "priezvisko", label: "Priezvisko", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 3, rowNumber: 1, widthPercent: 43 },
  { id: 12, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "titul_za", label: "Titul za menom", shortLabel: "Titul za", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 4, rowNumber: 1, widthPercent: 12 },
  { id: 13, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "rodne_cislo", label: "Rodné číslo", shortLabel: "Rod. číslo", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 5, rowNumber: 0, widthPercent: 100 },
  { id: 22, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "rodne_priezvisko", label: "Rodné priezvisko", shortLabel: "Rod. priez.", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 6, rowNumber: 2, widthPercent: 46.5 },
  { id: 14, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "datum_narodenia", label: "Dátum narodenia", shortLabel: "Dát. nar.", fieldType: "date", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 7, rowNumber: 2, widthPercent: 23.5 },
  { id: 15, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "vek", label: "Vek", fieldType: "number", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 8, rowNumber: 2, widthPercent: 10 },
  { id: 21, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "pohlavie", label: "Pohlavie", fieldType: "jedna_moznost", isRequired: false, isHidden: false, options: ["muž", "žena"], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 9, rowNumber: 2, widthPercent: 20 },
  { id: 20, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "miesto_narodenia", label: "Miesto narodenia", shortLabel: "Miesto nar.", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 10, rowNumber: 3, widthPercent: 50 },
  { id: 16, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_OSOBNE, fieldKey: "statna_prislusnost", label: "Štátna príslušnosť", shortLabel: "Št. príslušnosť", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 11, rowNumber: 3, widthPercent: 50 },
  { id: 17, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_DOKLADY, fieldKey: "typ_dokladu", label: "Typ dokladu totožnosti", shortLabel: "Typ dokladu", fieldType: "jedna_moznost", isRequired: true, isHidden: false, options: ["Občiansky preukaz", "Cestovný pas", "Vodičský preukaz", "Povolenie na pobyt", "Preukaz diplomata", "Iný"], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 20 },
  { id: 120, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_DOKLADY, fieldKey: "typ_dokladu_iny", label: "Špecifikácia dokladu", shortLabel: "Špecifikácia", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "typ_dokladu", value: "Iný" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0.5, rowNumber: 0, widthPercent: 20 },
  { id: 18, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_DOKLADY, fieldKey: "cislo_dokladu", label: "Číslo dokladu totožnosti", shortLabel: "Č. dokladu", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 30 },
  { id: 19, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_DOKLADY, fieldKey: "platnost_dokladu", label: "Platnosť dokladu do", shortLabel: "Platnosť do", fieldType: "date", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 2, rowNumber: 0, widthPercent: 20 },
  { id: 112, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_DOKLADY, fieldKey: "vydal_organ", label: "Vydal (orgán)", shortLabel: "Vydal", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 3, rowNumber: 0, widthPercent: 30 },
  { id: 110, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_DOKLADY, fieldKey: "kod_vydavajuceho_organu", label: "Kód vydávajúceho orgánu", shortLabel: "Kód orgánu", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 4, rowNumber: 1, widthPercent: 100 },
  { id: 23, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "tp_ulica", label: "Ulica (trvalý pobyt)", shortLabel: "Ulica", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 9, rowNumber: 0, widthPercent: 100 },
  { id: 24, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "tp_supisne", label: "Súpisné číslo", shortLabel: "Súpisné č.", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 10, rowNumber: 0, widthPercent: 100 },
  { id: 25, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "tp_orientacne", label: "Orientačné číslo", shortLabel: "Orient. č.", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 11, rowNumber: 0, widthPercent: 100 },
  { id: 26, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "tp_mesto", label: "Mesto", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 12, rowNumber: 0, widthPercent: 100 },
  { id: 27, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "tp_psc", label: "PSČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 13, rowNumber: 0, widthPercent: 100 },
  { id: 28, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "tp_stat", label: "Štát", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 14, rowNumber: 0, widthPercent: 100 },
  { id: 29, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "korespond_rovnaka", label: "Adresa prech. pobytu sa zhoduje s trvalou", shortLabel: "Prech. = trvalá", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 16, rowNumber: 0, widthPercent: 100 },
  { id: 30, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "ka_ulica", label: "Ulica (prechodný pobyt)", shortLabel: "Ulica (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 18, rowNumber: 0, widthPercent: 100 },
  { id: 31, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "ka_supisne", label: "Súpisné číslo (prechodný)", shortLabel: "Súp. č. (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 19, rowNumber: 0, widthPercent: 100 },
  { id: 32, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "ka_orientacne", label: "Orientačné číslo (prechodný)", shortLabel: "Or. č. (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 20, rowNumber: 0, widthPercent: 100 },
  { id: 33, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "ka_mesto", label: "Mesto (prechodný)", shortLabel: "Mesto (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 22, rowNumber: 0, widthPercent: 100 },
  { id: 34, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "ka_psc", label: "PSČ (prechodný)", shortLabel: "PSČ (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 25, rowNumber: 0, widthPercent: 100 },
  { id: 35, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "ka_stat", label: "Štát (prechodný)", shortLabel: "Štát (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 27, rowNumber: 0, widthPercent: 100 },
  { id: 36, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "kontaktna_rovnaka", label: "Kontaktná adresa sa zhoduje s trvalou", shortLabel: "Kontakt. = trvalá", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 29, rowNumber: 0, widthPercent: 100 },
  { id: 37, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "koa_ulica", label: "Ulica (kontaktná)", shortLabel: "Ulica (kont.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "kontaktna_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 31, rowNumber: 0, widthPercent: 100 },
  { id: 38, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "koa_supisne", label: "Súpisné číslo (kontaktná)", shortLabel: "Súp. č. (kont.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "kontaktna_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 32, rowNumber: 0, widthPercent: 100 },
  { id: 39, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "koa_orientacne", label: "Orientačné číslo (kontaktná)", shortLabel: "Or. č. (kont.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "kontaktna_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 33, rowNumber: 0, widthPercent: 100 },
  { id: 40, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "koa_mesto", label: "Mesto (kontaktná)", shortLabel: "Mesto (kont.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "kontaktna_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 34, rowNumber: 0, widthPercent: 100 },
  { id: 41, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "koa_psc", label: "PSČ (kontaktná)", shortLabel: "PSČ (kont.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "kontaktna_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 35, rowNumber: 0, widthPercent: 100 },
  { id: 42, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_ADRESA, fieldKey: "koa_stat", label: "Štát (kontaktná)", shortLabel: "Štát (kont.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "kontaktna_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 36, rowNumber: 0, widthPercent: 100 },
  { id: 43, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_KONTAKT, fieldKey: "telefon", label: "Telefónne číslo (primárne)", shortLabel: "Tel. číslo", fieldType: "phone", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 8, rowNumber: 1, widthPercent: 100 },
  { id: 44, clientTypeId: 1, sectionId: FO_SECTION_POVINNE, panelId: FO_PANEL_KONTAKT, fieldKey: "email", label: "Email (primárny)", shortLabel: "Email", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 10, rowNumber: 0, widthPercent: 100 },
  { id: 200, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_RODINA, fieldKey: "rodinny_kontakt_meno", label: "Meno rodinného kontaktu", shortLabel: "Rod. kontakt", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "komunikacne", sortOrder: 0, rowNumber: 0, widthPercent: 50 },
  { id: 201, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_RODINA, fieldKey: "rodinny_kontakt_telefon", label: "Telefón rodinného kontaktu", shortLabel: "Rod. telefón", fieldType: "phone", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "komunikacne", sortOrder: 1, rowNumber: 0, widthPercent: 50 },
  { id: 202, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_RODINA, fieldKey: "rodinny_kontakt_vztah", label: "Vzťah", shortLabel: "Vzťah", fieldType: "jedna_moznost", isRequired: false, isHidden: false, options: ["Manžel/ka", "Partner/ka", "Rodič", "Dieťa", "Súrodenec", "Iný"], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "komunikacne", sortOrder: 2, rowNumber: 1, widthPercent: 50 },
  { id: 203, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_RODINA, fieldKey: "zastihnutie", label: "Najlepšie zastihnutie", shortLabel: "Zastihnutie", fieldType: "jedna_moznost", isRequired: false, isHidden: false, options: ["Ráno (8-12)", "Poobede (12-17)", "Večer (17-21)", "Kedykoľvek"], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "komunikacne", sortOrder: 3, rowNumber: 1, widthPercent: 50 },
  { id: 204, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_DORUCOVACIA, fieldKey: "doruc_rovnaka", label: "Doručovacia adresa sa zhoduje s trvalou", shortLabel: "Doruč. = trvalá", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "geolokacne", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 205, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_DORUCOVACIA, fieldKey: "doruc_ulica", label: "Ulica (doručovacia)", shortLabel: "Ulica (doruč.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "doruc_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "geolokacne", sortOrder: 1, rowNumber: 0, widthPercent: 100 },
  { id: 206, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_DORUCOVACIA, fieldKey: "doruc_mesto", label: "Mesto (doručovacia)", shortLabel: "Mesto (doruč.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "doruc_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "geolokacne", sortOrder: 2, rowNumber: 0, widthPercent: 100 },
  { id: 207, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_DORUCOVACIA, fieldKey: "doruc_psc", label: "PSČ (doručovacia)", shortLabel: "PSČ (doruč.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "doruc_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "geolokacne", sortOrder: 3, rowNumber: 0, widthPercent: 100 },
  { id: 208, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_DORUCOVACIA, fieldKey: "doruc_stat", label: "Štát (doručovacia)", shortLabel: "Štát (doruč.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "doruc_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "geolokacne", sortOrder: 4, rowNumber: 0, widthPercent: 100 },
  { id: 500, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_AML, fieldKey: "pep", label: "Politicky exponovaná osoba (PEP)", shortLabel: "PEP", fieldType: "jedna_moznost", isRequired: false, isHidden: false, options: ["Áno", "Nie"], defaultValue: "Nie", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 0, rowNumber: 0, widthPercent: 33 },
  { id: 501, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_AML, fieldKey: "pep_funkcia", label: "PEP – verejná funkcia", shortLabel: "PEP funkcia", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "pep", value: "Áno" }, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 1, rowNumber: 0, widthPercent: 33 },
  { id: 502, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_AML, fieldKey: "pep_vztah", label: "PEP – vzťah k PEP osobe", shortLabel: "PEP vzťah", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "pep", value: "Áno" }, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 2, rowNumber: 0, widthPercent: 33 },
  { id: 503, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_AML, fieldKey: "kuv_meno_1", label: "KUV 1 – Meno a priezvisko", shortLabel: "KUV 1 Meno", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 3, rowNumber: 1, widthPercent: 40 },
  { id: 504, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_AML, fieldKey: "kuv_rc_1", label: "KUV 1 – Rodné číslo", shortLabel: "KUV 1 RČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 4, rowNumber: 1, widthPercent: 30 },
  { id: 505, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_AML, fieldKey: "kuv_podiel_1", label: "KUV 1 – % podiel", shortLabel: "KUV 1 %", fieldType: "desatinne_cislo", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: "%", decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 5, rowNumber: 1, widthPercent: 30 },
  { id: 510, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZAKONNE, fieldKey: "dic", label: "DIČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 0, rowNumber: 0, widthPercent: 50 },
  { id: 511, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZAKONNE, fieldKey: "ic_dph", label: "IČ DPH", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 1, rowNumber: 0, widthPercent: 50 },
  { id: 512, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZAKONNE, fieldKey: "suhlas_gdpr", label: "Súhlas so spracovaním osobných údajov (GDPR)", shortLabel: "GDPR súhlas", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 2, rowNumber: 1, widthPercent: 50 },
  { id: 513, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZAKONNE, fieldKey: "suhlas_marketing", label: "Súhlas s marketingovou komunikáciou", shortLabel: "Marketing súhlas", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 3, rowNumber: 1, widthPercent: 50 },
  { id: 514, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZAKONNE, fieldKey: "suhlas_tretie_strany", label: "Súhlas s poskytnutím údajov tretím stranám", shortLabel: "Tretie strany", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 4, rowNumber: 2, widthPercent: 50 },
  { id: 515, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZAKONNE, fieldKey: "suhlas_profilovanie", label: "Súhlas s automatizovaným profilovaním", shortLabel: "Profilovanie", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 5, rowNumber: 2, widthPercent: 50 },
  { id: 516, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZAKONNE, fieldKey: "poistna_povinnost", label: "Poistná povinnosť splnená", shortLabel: "Poistná pov.", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 6, rowNumber: 3, widthPercent: 50 },
  { id: 517, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZAKONNE, fieldKey: "overenie_totoznosti", label: "Overenie totožnosti vykonané", shortLabel: "Overenie totoži.", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 7, rowNumber: 3, widthPercent: 50 },
  { id: 520, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZMLUVNE, fieldKey: "iban", label: "IBAN", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zmluvne", sortOrder: 0, rowNumber: 0, widthPercent: 40 },
  { id: 521, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZMLUVNE, fieldKey: "bic", label: "BIC/SWIFT", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zmluvne", sortOrder: 1, rowNumber: 0, widthPercent: 30 },
  { id: 522, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_ZMLUVNE, fieldKey: "cislo_uctu", label: "Číslo účtu", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zmluvne", sortOrder: 2, rowNumber: 0, widthPercent: 30 },
  { id: 530, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_MAJETKOVE, fieldKey: "spz", label: "ŠPZ / EČV", shortLabel: "ŠPZ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "majetkove", sortOrder: 0, rowNumber: 0, widthPercent: 50 },
  { id: 531, clientTypeId: 1, sectionId: FO_SECTION_DOPLNKOVE, panelId: FO_PANEL_MAJETKOVE, fieldKey: "vin", label: "VIN", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "majetkove", sortOrder: 1, rowNumber: 0, widthPercent: 50 },
  { id: 209, clientTypeId: 1, sectionId: FO_SECTION_VOLITELNE, panelId: null, fieldKey: "cgn_rating", label: "CGN Rating", shortLabel: "CGN", fieldType: "jedna_moznost", isRequired: false, isHidden: false, options: ["A", "B", "C", "D", "E"], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "volitelne", categoryCode: "bonita", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
];

export const SZCO_SECTIONS: StaticSection[] = [
  { id: SZCO_SECTION_POVINNE, clientTypeId: 3, name: "POVINNÉ ÚDAJE", folderCategory: "povinne", sortOrder: 0 },
  { id: SZCO_SECTION_DOPLNKOVE, clientTypeId: 3, name: "DOPLNKOVÉ ÚDAJE", folderCategory: "doplnkove", sortOrder: 1 },
  { id: SZCO_SECTION_VOLITELNE, clientTypeId: 3, name: "VOLITEĽNÉ ÚDAJE", folderCategory: "volitelne", sortOrder: 2 },
];

export const SZCO_PANELS: StaticPanel[] = [
  { id: SZCO_PANEL_SUBJEKT, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, name: "Subjekt SZČO", gridColumns: 3, sortOrder: 0 },
  { id: SZCO_PANEL_SIDLO, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, name: "Sídlo spoločnosti", gridColumns: 4, sortOrder: 1 },
  { id: SZCO_PANEL_OSOBNE, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, name: "Osobné údaje", gridColumns: 4, sortOrder: 2 },
  { id: SZCO_PANEL_ADRESA, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, name: "Adresa trvalého pobytu", gridColumns: 4, sortOrder: 3 },
  { id: SZCO_PANEL_DOKLADY, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, name: "Doklady", gridColumns: 4, sortOrder: 4 },
  { id: SZCO_PANEL_KONTAKT, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, name: "Kontaktné údaje", gridColumns: 2, sortOrder: 5 },
  { id: SZCO_PANEL_AML, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, name: "AML – Konečný užívateľ výhod", gridColumns: 3, sortOrder: 2 },
  { id: SZCO_PANEL_FIREMNY, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, name: "Firemný profil", gridColumns: 3, sortOrder: 3 },
  { id: SZCO_PANEL_ZAKONNE, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, name: "Zákonné údaje", gridColumns: 2, sortOrder: 0 },
  { id: SZCO_PANEL_ZMLUVNE, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, name: "Bankové údaje", gridColumns: 3, sortOrder: 1 },
];

export const SZCO_FIELDS: StaticField[] = [
  { id: 45, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SUBJEKT, fieldKey: "nazov_organizacie", label: "Názov organizácie", shortLabel: "Názov org.", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 46, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SUBJEKT, fieldKey: "ico", label: "IČO", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 100 },
  { id: 47, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SUBJEKT, fieldKey: "sk_nace", label: "SK NACE", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", categoryCode: "firemny_profil", sortOrder: 2, rowNumber: 0, widthPercent: 100 },
  { id: 48, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "sidlo_ulica", label: "Ulica (sídlo)", shortLabel: "Ulica", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 49, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "sidlo_supisne", label: "Súpisné číslo", shortLabel: "Súpisné č.", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 100 },
  { id: 50, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "sidlo_orientacne", label: "Orientačné číslo", shortLabel: "Orient. č.", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 2, rowNumber: 0, widthPercent: 100 },
  { id: 51, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "sidlo_mesto", label: "Mesto/Obec", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 3, rowNumber: 0, widthPercent: 100 },
  { id: 52, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "sidlo_psc", label: "PSČ", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 4, rowNumber: 0, widthPercent: 100 },
  { id: 53, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "sidlo_stat", label: "Štát", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 5, rowNumber: 0, widthPercent: 100 },
  { id: 54, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "vykon_rovnaky", label: "Adresa výkonu činnosti sa zhoduje so sídlom", shortLabel: "Výkon = sídlo", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 6, rowNumber: 0, widthPercent: 100 },
  { id: 55, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "vykon_ulica", label: "Ulica (výkon činnosti)", shortLabel: "Ulica (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 7, rowNumber: 0, widthPercent: 100 },
  { id: 56, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "vykon_supisne", label: "Súpisné číslo (výkon)", shortLabel: "Súp. č. (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 8, rowNumber: 0, widthPercent: 100 },
  { id: 57, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "vykon_orientacne", label: "Orientačné číslo (výkon)", shortLabel: "Or. č. (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 9, rowNumber: 0, widthPercent: 100 },
  { id: 58, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "vykon_mesto", label: "Mesto/Obec (výkon)", shortLabel: "Mesto (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 10, rowNumber: 0, widthPercent: 100 },
  { id: 59, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "vykon_psc", label: "PSČ (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 11, rowNumber: 0, widthPercent: 100 },
  { id: 60, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_SIDLO, fieldKey: "vykon_stat", label: "Štát (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 12, rowNumber: 0, widthPercent: 100 },
  { id: 61, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_OSOBNE, fieldKey: "titul_pred", label: "Titul pred menom", shortLabel: "Titul pred", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 62, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_OSOBNE, fieldKey: "meno", label: "Meno", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 100 },
  { id: 63, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_OSOBNE, fieldKey: "priezvisko", label: "Priezvisko", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 3, rowNumber: 0, widthPercent: 100 },
  { id: 64, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_OSOBNE, fieldKey: "titul_za", label: "Titul za menom", shortLabel: "Titul za", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 4, rowNumber: 0, widthPercent: 100 },
  { id: 65, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_OSOBNE, fieldKey: "rodne_cislo", label: "Rodné číslo", shortLabel: "Rod. číslo", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 4, rowNumber: 0, widthPercent: 100 },
  { id: 66, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_OSOBNE, fieldKey: "datum_narodenia", label: "Dátum narodenia", shortLabel: "Dát. narodenia", fieldType: "date", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 5, rowNumber: 0, widthPercent: 100 },
  { id: 67, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_OSOBNE, fieldKey: "vek", label: "Vek", fieldType: "number", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 6, rowNumber: 0, widthPercent: 100 },
  { id: 68, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_OSOBNE, fieldKey: "statna_prislusnost", label: "Štátna príslušnosť", shortLabel: "Št. príslušnosť", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 7, rowNumber: 0, widthPercent: 100 },
  { id: 69, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_DOKLADY, fieldKey: "typ_dokladu", label: "Typ dokladu totožnosti", shortLabel: "Typ dokladu", fieldType: "jedna_moznost", isRequired: true, isHidden: false, options: ["Občiansky preukaz", "Cestovný pas", "Vodičský preukaz", "Povolenie na pobyt", "Preukaz diplomata", "Iný"], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 20 },
  { id: 121, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_DOKLADY, fieldKey: "typ_dokladu_iny", label: "Špecifikácia dokladu", shortLabel: "Špecifikácia", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "typ_dokladu", value: "Iný" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0.5, rowNumber: 0, widthPercent: 20 },
  { id: 70, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_DOKLADY, fieldKey: "cislo_dokladu", label: "Číslo dokladu totožnosti", shortLabel: "Č. dokladu", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 30 },
  { id: 71, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_DOKLADY, fieldKey: "platnost_dokladu", label: "Platnosť dokladu do", shortLabel: "Platnosť do", fieldType: "date", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 2, rowNumber: 0, widthPercent: 20 },
  { id: 113, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_DOKLADY, fieldKey: "vydal_organ", label: "Vydal (orgán)", shortLabel: "Vydal", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 3, rowNumber: 0, widthPercent: 30 },
  { id: 111, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_DOKLADY, fieldKey: "kod_vydavajuceho_organu", label: "Kód vydávajúceho orgánu", shortLabel: "Kód orgánu", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 4, rowNumber: 1, widthPercent: 100 },
  { id: 72, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "tp_ulica", label: "Ulica (trvalý pobyt)", shortLabel: "Ulica", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 73, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "tp_supisne", label: "Súpisné číslo", shortLabel: "Súpisné č.", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 100 },
  { id: 74, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "tp_orientacne", label: "Orientačné číslo", shortLabel: "Orient. č.", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 2, rowNumber: 0, widthPercent: 100 },
  { id: 75, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "tp_mesto", label: "Mesto", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 3, rowNumber: 0, widthPercent: 100 },
  { id: 76, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "tp_psc", label: "PSČ", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 4, rowNumber: 0, widthPercent: 100 },
  { id: 77, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "tp_stat", label: "Štát", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 5, rowNumber: 0, widthPercent: 100 },
  { id: 78, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "korespond_rovnaka", label: "Adresa prech. pobytu sa zhoduje s trvalou", shortLabel: "Prech. = trvalá", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 6, rowNumber: 0, widthPercent: 100 },
  { id: 79, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "ka_ulica", label: "Ulica (prechodný)", shortLabel: "Ulica (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 7, rowNumber: 0, widthPercent: 100 },
  { id: 80, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "ka_supisne", label: "Súpisné číslo (prechodný)", shortLabel: "Súp. č. (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 8, rowNumber: 0, widthPercent: 100 },
  { id: 81, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "ka_orientacne", label: "Orientačné číslo (prechodný)", shortLabel: "Or. č. (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 9, rowNumber: 0, widthPercent: 100 },
  { id: 82, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "ka_mesto", label: "Mesto (prechodný)", shortLabel: "Mesto (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 10, rowNumber: 0, widthPercent: 100 },
  { id: 83, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_ADRESA, fieldKey: "ka_psc", label: "PSČ (prechodný)", shortLabel: "PSČ (prech.)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "korespond_rovnaka", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 11, rowNumber: 0, widthPercent: 100 },
  { id: 84, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_KONTAKT, fieldKey: "telefon", label: "Telefónne číslo (primárne)", shortLabel: "Tel. číslo", fieldType: "phone", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 85, clientTypeId: 3, sectionId: SZCO_SECTION_POVINNE, panelId: SZCO_PANEL_KONTAKT, fieldKey: "email", label: "Email (primárny)", shortLabel: "Email", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 100 },
  { id: 210, clientTypeId: 3, sectionId: SZCO_SECTION_VOLITELNE, panelId: null, fieldKey: "cgn_rating", label: "CGN Rating", shortLabel: "CGN", fieldType: "jedna_moznost", isRequired: false, isHidden: false, options: ["A", "B", "C", "D", "E"], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "volitelne", categoryCode: "bonita", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 600, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZAKONNE, fieldKey: "dic", label: "DIČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 0, rowNumber: 0, widthPercent: 50 },
  { id: 601, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZAKONNE, fieldKey: "ic_dph", label: "IČ DPH", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 1, rowNumber: 0, widthPercent: 50 },
  { id: 602, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZAKONNE, fieldKey: "suhlas_gdpr", label: "Súhlas so spracovaním osobných údajov (GDPR)", shortLabel: "GDPR súhlas", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 2, rowNumber: 1, widthPercent: 50 },
  { id: 603, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZAKONNE, fieldKey: "suhlas_marketing", label: "Súhlas s marketingovou komunikáciou", shortLabel: "Marketing súhlas", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 3, rowNumber: 1, widthPercent: 50 },
  { id: 604, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZAKONNE, fieldKey: "suhlas_tretie_strany", label: "Súhlas s poskytnutím údajov tretím stranám", shortLabel: "Tretie strany", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 4, rowNumber: 2, widthPercent: 50 },
  { id: 605, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZAKONNE, fieldKey: "suhlas_profilovanie", label: "Súhlas s automatizovaným profilovaním", shortLabel: "Profilovanie", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 5, rowNumber: 2, widthPercent: 50 },
  { id: 606, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZAKONNE, fieldKey: "poistna_povinnost", label: "Poistná povinnosť splnená", shortLabel: "Poistná pov.", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 6, rowNumber: 3, widthPercent: 50 },
  { id: 607, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZAKONNE, fieldKey: "overenie_totoznosti", label: "Overenie totožnosti vykonané", shortLabel: "Overenie totoži.", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 7, rowNumber: 3, widthPercent: 50 },
  { id: 610, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZMLUVNE, fieldKey: "iban", label: "IBAN", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zmluvne", sortOrder: 0, rowNumber: 0, widthPercent: 40 },
  { id: 611, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZMLUVNE, fieldKey: "bic", label: "BIC/SWIFT", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zmluvne", sortOrder: 1, rowNumber: 0, widthPercent: 30 },
  { id: 612, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_ZMLUVNE, fieldKey: "cislo_uctu", label: "Číslo účtu", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zmluvne", sortOrder: 2, rowNumber: 0, widthPercent: 30 },
  { id: 300, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_AML, fieldKey: "kuv_meno_1", label: "KUV 1 – Meno a priezvisko", shortLabel: "KUV 1 Meno", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 0, rowNumber: 0, widthPercent: 40 },
  { id: 301, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_AML, fieldKey: "kuv_rc_1", label: "KUV 1 – Rodné číslo", shortLabel: "KUV 1 RČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 1, rowNumber: 0, widthPercent: 30 },
  { id: 302, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_AML, fieldKey: "kuv_podiel_1", label: "KUV 1 – % podiel", shortLabel: "KUV 1 %", fieldType: "desatinne_cislo", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: "%", decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 2, rowNumber: 0, widthPercent: 30 },
  { id: 303, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_AML, fieldKey: "kuv_meno_2", label: "KUV 2 – Meno a priezvisko", shortLabel: "KUV 2 Meno", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 3, rowNumber: 1, widthPercent: 40 },
  { id: 304, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_AML, fieldKey: "kuv_rc_2", label: "KUV 2 – Rodné číslo", shortLabel: "KUV 2 RČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 4, rowNumber: 1, widthPercent: 30 },
  { id: 305, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_AML, fieldKey: "kuv_podiel_2", label: "KUV 2 – % podiel", shortLabel: "KUV 2 %", fieldType: "desatinne_cislo", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: "%", decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 5, rowNumber: 1, widthPercent: 30 },
  { id: 306, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_AML, fieldKey: "kuv_meno_3", label: "KUV 3 – Meno a priezvisko", shortLabel: "KUV 3 Meno", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 6, rowNumber: 2, widthPercent: 40 },
  { id: 307, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_AML, fieldKey: "kuv_rc_3", label: "KUV 3 – Rodné číslo", shortLabel: "KUV 3 RČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 7, rowNumber: 2, widthPercent: 30 },
  { id: 308, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_AML, fieldKey: "kuv_podiel_3", label: "KUV 3 – % podiel", shortLabel: "KUV 3 %", fieldType: "desatinne_cislo", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: "%", decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 8, rowNumber: 2, widthPercent: 30 },
  { id: 320, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_FIREMNY, fieldKey: "obrat", label: "Obrat (ročný)", shortLabel: "Obrat", fieldType: "desatinne_cislo", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: "€", decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "firemny_profil", sortOrder: 0, rowNumber: 0, widthPercent: 33 },
  { id: 321, clientTypeId: 3, sectionId: SZCO_SECTION_DOPLNKOVE, panelId: SZCO_PANEL_FIREMNY, fieldKey: "pocet_zamestnancov", label: "Počet zamestnancov", shortLabel: "Zamestnanci", fieldType: "number", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 0, fieldCategory: "doplnkove", categoryCode: "firemny_profil", sortOrder: 1, rowNumber: 0, widthPercent: 33 },
];

export const PO_SECTIONS: StaticSection[] = [
  { id: PO_SECTION_POVINNE, clientTypeId: 4, name: "POVINNÉ ÚDAJE", folderCategory: "povinne", sortOrder: 0 },
  { id: PO_SECTION_DOPLNKOVE, clientTypeId: 4, name: "DOPLNKOVÉ ÚDAJE", folderCategory: "doplnkove", sortOrder: 1 },
  { id: PO_SECTION_VOLITELNE, clientTypeId: 4, name: "VOLITEĽNÉ ÚDAJE", folderCategory: "volitelne", sortOrder: 2 },
];

export const PO_PANELS: StaticPanel[] = [
  { id: PO_PANEL_SUBJEKT, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, name: "Subjekt PO", gridColumns: 2, sortOrder: 0 },
  { id: PO_PANEL_SIDLO, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, name: "Sídlo spoločnosti", gridColumns: 2, sortOrder: 1 },
  { id: PO_PANEL_KONTAKT, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, name: "Kontaktné údaje", gridColumns: 2, sortOrder: 2 },
  { id: PO_PANEL_AML, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, name: "AML – Konečný užívateľ výhod", gridColumns: 3, sortOrder: 2 },
  { id: PO_PANEL_FIREMNY, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, name: "Firemný profil", gridColumns: 3, sortOrder: 3 },
  { id: PO_PANEL_ZAKONNE, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, name: "Zákonné údaje", gridColumns: 2, sortOrder: 0 },
  { id: PO_PANEL_ZMLUVNE, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, name: "Bankové údaje", gridColumns: 3, sortOrder: 1 },
  { id: PO_PANEL_STATUTARI, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, name: "Štatutárni zástupcovia", gridColumns: 3, sortOrder: 4 },
];

export const PO_FIELDS: StaticField[] = [
  { id: 87, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SUBJEKT, fieldKey: "nazov_organizacie", label: "Názov organizácie", shortLabel: "Názov org.", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 88, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SUBJEKT, fieldKey: "ico", label: "IČO", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 100 },
  { id: 89, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SUBJEKT, fieldKey: "sk_nace", label: "SK NACE", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", categoryCode: "firemny_profil", sortOrder: 2, rowNumber: 0, widthPercent: 100 },
  { id: 90, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "sidlo_ulica", label: "Ulica (sídlo)", shortLabel: "Ulica", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 91, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "sidlo_supisne", label: "Súpisné číslo", shortLabel: "Súpisné č.", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 100 },
  { id: 92, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "sidlo_orientacne", label: "Orientačné číslo", shortLabel: "Orient. č.", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 2, rowNumber: 0, widthPercent: 100 },
  { id: 93, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "sidlo_mesto", label: "Mesto/Obec", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 3, rowNumber: 0, widthPercent: 100 },
  { id: 94, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "sidlo_psc", label: "PSČ", fieldType: "short_text", isRequired: true, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 4, rowNumber: 0, widthPercent: 100 },
  { id: 95, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "sidlo_stat", label: "Štát", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 5, rowNumber: 0, widthPercent: 100 },
  { id: 96, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "vykon_rovnaky", label: "Adresa výkonu činnosti sa zhoduje so sídlom", shortLabel: "Výkon = sídlo", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 6, rowNumber: 0, widthPercent: 100 },
  { id: 97, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "vykon_ulica", label: "Ulica (výkon činnosti)", shortLabel: "Ulica (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 7, rowNumber: 0, widthPercent: 100 },
  { id: 98, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "vykon_supisne", label: "Súpisné číslo (výkon)", shortLabel: "Súp. č. (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 8, rowNumber: 0, widthPercent: 100 },
  { id: 99, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "vykon_orientacne", label: "Orientačné číslo (výkon)", shortLabel: "Or. č. (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 9, rowNumber: 0, widthPercent: 100 },
  { id: 100, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "vykon_mesto", label: "Mesto/Obec (výkon)", shortLabel: "Mesto (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 10, rowNumber: 0, widthPercent: 100 },
  { id: 101, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "vykon_psc", label: "PSČ (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 11, rowNumber: 0, widthPercent: 100 },
  { id: 102, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_SIDLO, fieldKey: "vykon_stat", label: "Štát (výkon)", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: { dependsOn: "vykon_rovnaky", value: "false" }, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 12, rowNumber: 0, widthPercent: 100 },
  { id: 103, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_KONTAKT, fieldKey: "telefon", label: "Telefónne číslo (primárne)", shortLabel: "Tel. číslo", fieldType: "phone", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 104, clientTypeId: 4, sectionId: PO_SECTION_POVINNE, panelId: PO_PANEL_KONTAKT, fieldKey: "email", label: "Email (primárny)", shortLabel: "Email", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "povinne", sortOrder: 1, rowNumber: 0, widthPercent: 100 },
  { id: 211, clientTypeId: 4, sectionId: PO_SECTION_VOLITELNE, panelId: null, fieldKey: "cgn_rating", label: "CGN Rating", shortLabel: "CGN", fieldType: "jedna_moznost", isRequired: false, isHidden: false, options: ["A", "B", "C", "D", "E"], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "volitelne", categoryCode: "bonita", sortOrder: 0, rowNumber: 0, widthPercent: 100 },
  { id: 700, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZAKONNE, fieldKey: "dic", label: "DIČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 0, rowNumber: 0, widthPercent: 50 },
  { id: 701, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZAKONNE, fieldKey: "ic_dph", label: "IČ DPH", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 1, rowNumber: 0, widthPercent: 50 },
  { id: 702, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZAKONNE, fieldKey: "suhlas_gdpr", label: "Súhlas so spracovaním osobných údajov (GDPR)", shortLabel: "GDPR súhlas", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 2, rowNumber: 1, widthPercent: 50 },
  { id: 703, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZAKONNE, fieldKey: "suhlas_marketing", label: "Súhlas s marketingovou komunikáciou", shortLabel: "Marketing súhlas", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 3, rowNumber: 1, widthPercent: 50 },
  { id: 704, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZAKONNE, fieldKey: "suhlas_tretie_strany", label: "Súhlas s poskytnutím údajov tretím stranám", shortLabel: "Tretie strany", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 4, rowNumber: 2, widthPercent: 50 },
  { id: 705, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZAKONNE, fieldKey: "suhlas_profilovanie", label: "Súhlas s automatizovaným profilovaním", shortLabel: "Profilovanie", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 5, rowNumber: 2, widthPercent: 50 },
  { id: 706, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZAKONNE, fieldKey: "poistna_povinnost", label: "Poistná povinnosť splnená", shortLabel: "Poistná pov.", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 6, rowNumber: 3, widthPercent: 50 },
  { id: 707, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZAKONNE, fieldKey: "overenie_totoznosti", label: "Overenie totožnosti vykonané", shortLabel: "Overenie totoži.", fieldType: "switch", isRequired: false, isHidden: false, options: [], defaultValue: "false", visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zakonne", sortOrder: 7, rowNumber: 3, widthPercent: 50 },
  { id: 710, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZMLUVNE, fieldKey: "iban", label: "IBAN", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zmluvne", sortOrder: 0, rowNumber: 0, widthPercent: 40 },
  { id: 711, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZMLUVNE, fieldKey: "bic", label: "BIC/SWIFT", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zmluvne", sortOrder: 1, rowNumber: 0, widthPercent: 30 },
  { id: 712, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_ZMLUVNE, fieldKey: "cislo_uctu", label: "Číslo účtu", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "zmluvne", sortOrder: 2, rowNumber: 0, widthPercent: 30 },
  { id: 720, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_STATUTARI, fieldKey: "statutar_meno_1", label: "Štatutár 1 – Meno a priezvisko", shortLabel: "Štatutár 1", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "pravne", sortOrder: 0, rowNumber: 0, widthPercent: 40 },
  { id: 721, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_STATUTARI, fieldKey: "statutar_rc_1", label: "Štatutár 1 – Rodné číslo", shortLabel: "Štatutár 1 RČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "pravne", sortOrder: 1, rowNumber: 0, widthPercent: 30 },
  { id: 722, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_STATUTARI, fieldKey: "statutar_funkcia_1", label: "Štatutár 1 – Funkcia", shortLabel: "Funkcia 1", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "pravne", sortOrder: 2, rowNumber: 0, widthPercent: 30 },
  { id: 723, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_STATUTARI, fieldKey: "statutar_meno_2", label: "Štatutár 2 – Meno a priezvisko", shortLabel: "Štatutár 2", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "pravne", sortOrder: 3, rowNumber: 1, widthPercent: 40 },
  { id: 724, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_STATUTARI, fieldKey: "statutar_rc_2", label: "Štatutár 2 – Rodné číslo", shortLabel: "Štatutár 2 RČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "pravne", sortOrder: 4, rowNumber: 1, widthPercent: 30 },
  { id: 725, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_STATUTARI, fieldKey: "statutar_funkcia_2", label: "Štatutár 2 – Funkcia", shortLabel: "Funkcia 2", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "pravne", sortOrder: 5, rowNumber: 1, widthPercent: 30 },
  { id: 400, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_AML, fieldKey: "kuv_meno_1", label: "KUV 1 – Meno a priezvisko", shortLabel: "KUV 1 Meno", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 0, rowNumber: 0, widthPercent: 40 },
  { id: 401, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_AML, fieldKey: "kuv_rc_1", label: "KUV 1 – Rodné číslo", shortLabel: "KUV 1 RČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 1, rowNumber: 0, widthPercent: 30 },
  { id: 402, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_AML, fieldKey: "kuv_podiel_1", label: "KUV 1 – % podiel", shortLabel: "KUV 1 %", fieldType: "desatinne_cislo", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: "%", decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 2, rowNumber: 0, widthPercent: 30 },
  { id: 403, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_AML, fieldKey: "kuv_meno_2", label: "KUV 2 – Meno a priezvisko", shortLabel: "KUV 2 Meno", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 3, rowNumber: 1, widthPercent: 40 },
  { id: 404, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_AML, fieldKey: "kuv_rc_2", label: "KUV 2 – Rodné číslo", shortLabel: "KUV 2 RČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 4, rowNumber: 1, widthPercent: 30 },
  { id: 405, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_AML, fieldKey: "kuv_podiel_2", label: "KUV 2 – % podiel", shortLabel: "KUV 2 %", fieldType: "desatinne_cislo", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: "%", decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 5, rowNumber: 1, widthPercent: 30 },
  { id: 406, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_AML, fieldKey: "kuv_meno_3", label: "KUV 3 – Meno a priezvisko", shortLabel: "KUV 3 Meno", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 6, rowNumber: 2, widthPercent: 40 },
  { id: 407, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_AML, fieldKey: "kuv_rc_3", label: "KUV 3 – Rodné číslo", shortLabel: "KUV 3 RČ", fieldType: "short_text", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 7, rowNumber: 2, widthPercent: 30 },
  { id: 408, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_AML, fieldKey: "kuv_podiel_3", label: "KUV 3 – % podiel", shortLabel: "KUV 3 %", fieldType: "desatinne_cislo", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: "%", decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "aml", sortOrder: 8, rowNumber: 2, widthPercent: 30 },
  { id: 420, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_FIREMNY, fieldKey: "obrat", label: "Obrat (ročný)", shortLabel: "Obrat", fieldType: "desatinne_cislo", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: "€", decimalPlaces: 2, fieldCategory: "doplnkove", categoryCode: "firemny_profil", sortOrder: 0, rowNumber: 0, widthPercent: 33 },
  { id: 421, clientTypeId: 4, sectionId: PO_SECTION_DOPLNKOVE, panelId: PO_PANEL_FIREMNY, fieldKey: "pocet_zamestnancov", label: "Počet zamestnancov", shortLabel: "Zamestnanci", fieldType: "number", isRequired: false, isHidden: false, options: [], defaultValue: null, visibilityRule: null, unit: null, decimalPlaces: 0, fieldCategory: "doplnkove", categoryCode: "firemny_profil", sortOrder: 1, rowNumber: 0, widthPercent: 33 },
];

export function getFieldsForType(clientType: string): StaticField[] {
  switch (clientType) {
    case "fo": return FO_FIELDS;
    case "szco": return SZCO_FIELDS;
    case "po": return PO_FIELDS;
    default: return FO_FIELDS;
  }
}

export function getSectionsForType(clientType: string): StaticSection[] {
  switch (clientType) {
    case "fo": return FO_SECTIONS;
    case "szco": return SZCO_SECTIONS;
    case "po": return PO_SECTIONS;
    default: return FO_SECTIONS;
  }
}

export function getPanelsForType(clientType: string): StaticPanel[] {
  switch (clientType) {
    case "fo": return FO_PANELS;
    case "szco": return SZCO_PANELS;
    case "po": return PO_PANELS;
    default: return FO_PANELS;
  }
}

export function getFieldsForClientTypeId(clientTypeId: number): StaticField[] {
  switch (clientTypeId) {
    case 1: return FO_FIELDS;
    case 3: return SZCO_FIELDS;
    case 4: return PO_FIELDS;
    default: return FO_FIELDS;
  }
}

export function getSectionsForClientTypeId(clientTypeId: number): StaticSection[] {
  switch (clientTypeId) {
    case 1: return FO_SECTIONS;
    case 3: return SZCO_SECTIONS;
    case 4: return PO_SECTIONS;
    default: return FO_SECTIONS;
  }
}

export function getPanelsForClientTypeId(clientTypeId: number): StaticPanel[] {
  switch (clientTypeId) {
    case 1: return FO_PANELS;
    case 3: return SZCO_PANELS;
    case 4: return PO_PANELS;
    default: return FO_PANELS;
  }
}
